export const GET_ADD_NEW_COLOR_REQUEST = 'GET_ADD_NEW_COLOR_REQUEST'
export const GET_ADD_NEW_COLOR_SUCCESS = 'GET_ADD_NEW_COLOR_SUCCESS'
export const GET_ADD_NEW_COLOR_FAILURE = 'GET_ADD_NEW_COLOR_FAILURE'

